services:
  api:
    container_name: chat-socket
    image: chat-socket:0.0.1
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    ports:
      - 3005:3005
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
